name: Refresh feeds

on:
  schedule:
    - cron: "0 2 * * *"   # 每天 10:00(UTC+8) 运行
  workflow_dispatch:      # 允许手动触发

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collectors
        run: |
          python -m freshfeeds bili timeline --limit 20 --format all --outdir output
          python -m freshfeeds bili rank --category bangumi --limit 20 --format md --outdir output
          python -m freshfeeds steam --limit 8 --format all --outdir output

      - name: Commit updated output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*
          git commit -m "chore: refresh feeds" || echo "No changes"
          git push
